
development:
  adapter: postgresql
  encoding: unicode
  database: relove_me_development
  pool: 5
  host: localhost
  username: mathildathompson
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: mathildathompson
#   pool: 5
#   password: